In [4]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('sales.csv')

In [10]:
df1=pd.read_csv('sales.csv',index_col=['Region','Order ID'])

In [8]:
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [11]:
df1

                                                           Country  \
Region                            Order ID
Australia and Oceania             669165933                 Tuvalu
Central America and the Caribbean 963881480                Grenada
Europe                            341417157                 Russia
Sub-Saharan Africa                514321792  Sao Tome and Principe
                                  115456712                 Rwanda
...                                                            ...
                                  512878119                   Mali
Asia                              810711038               Malaysia
Sub-Saharan Africa                728815257           Sierra Leone
North America                     559427106                 Mexico
Sub-Saharan Africa                665095412             Mozambique

                                                   Item Type Sales Channel  \
Region                            Order ID
Australia and Oceania             669165933        Baby Food       Offline
Central America and the Caribbean 963881480           Cereal        Online
Europe                            341417157  Office Supplies       Offline
Sub-Saharan Africa                514321792           Fruits        Online
                                  115456712  Office Supplies       Offline
...                                                      ...           ...
                                  512878119          Clothes        Online
Asia                              810711038           Fruits       Offline
Sub-Saharan Africa                728815257       Vegetables       Offline
North America                     559427106    Personal Care       Offline
Sub-Saharan Africa                665095412        Household       Offline

                                            Order Priority  Order Date  \
Region                            Order ID
Australia and Oceania             669165933              H   5/28/2010
Central America and the Caribbean 963881480              C   8/22/2012
Europe                            341417157              L    5/2/2014
Sub-Saharan Africa                514321792              C   6/20/2014
                                  115456712              L    2/1/2013
...                                                    ...         ...
                                  512878119              M   7/26/2011
Asia                              810711038              L  11/11/2011
Sub-Saharan Africa                728815257              C    6/1/2016
North America                     559427106              M   7/30/2015
Sub-Saharan Africa                665095412              L   2/10/2012

                                              Ship Date  Units Sold  \
Region                            Order ID
Australia and Oceania             669165933   6/27/2010        9925
Central America and the Caribbean 963881480   9/15/2012        2804
Europe                            341417157    5/8/2014        1779
Sub-Saharan Africa                514321792    7/5/2014        8102
                                  115456712    2/6/2013        5062
...                                                 ...         ...
                                  512878119    9/3/2011         888
Asia                              810711038  12/28/2011        6267
Sub-Saharan Africa                728815257   6/29/2016        1485
North America                     559427106    8/8/2015        5767
Sub-Saharan Africa                665095412   2/15/2012        5367

                                             Unit Price  Unit Cost  \
Region                            Order ID
Australia and Oceania             669165933      255.28     159.42
Central America and the Caribbean 963881480      205.70     117.11
Europe                            341417157      651.21     524.96
Sub-Saharan Africa                514321792        9.33       6.92
                                  115456712      651.21     524.96
...                                                 ...        ...
                                  512878119      109.28      35.84
Asia                              810711038        9.33       6.92
Sub-Saharan Africa                728815257      154.06      90.93
North America                     559427106       81.73      56.67
Sub-Saharan Africa                665095412      668.27     502.54

                                             Total Revenue  Total Cost  \
Region                            Order ID
Australia and Oceania             669165933     2533654.00  1582243.50
Central America and the Caribbean 963881480      576782.80   328376.44
Europe                            341417157     1158502.59   933903.84
Sub-Saharan Africa                514321792       75591.66    56065.84
                                  115456712     3296425.02  2657347.52
...                                                    ...         ...
                                  512878119       97040.64    31825.92
Asia                              810711038       58471.11    43367.64
Sub-Saharan Africa                728815257      228779.10   135031.05
North America                     559427106      471336.91   326815.89
Sub-Saharan Africa                665095412     3586605.09  2697132.18

                                             Total Profit
Region                            Order ID
Australia and Oceania             669165933     951410.50
Central America and the Caribbean 963881480     248406.36
Europe                            341417157     224598.75
Sub-Saharan Africa                514321792      19525.82
                                  115456712     639077.50
...                                                   ...
                                  512878119      65214.72
Asia                              810711038      15103.47
Sub-Saharan Africa                728815257      93748.05
North America                     559427106     144521.02
Sub-Saharan Africa                665095412     889472.91

[100 rows x 12 columns]

In [12]:
ht=pd.read_html('index.html')

ImportError: lxml not found, please install it